/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceCategory = IDL.Variant({
  'inStore' : IDL.Null,
  'online' : IDL.Null,
});
export const StoreServiceCategory = IDL.Variant({
  'operatorService' : IDL.Null,
  'selfService' : IDL.Null,
});
export const ImageType = IDL.Variant({
  'service' : IDL.Null,
  'hero' : IDL.Null,
  'logo' : IDL.Null,
  'contactBackground' : IDL.Null,
  'gallery' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const AspectRatioOption = IDL.Variant({
  'square' : IDL.Null,
  'portrait' : IDL.Null,
  'original' : IDL.Null,
  'landscape' : IDL.Null,
});
export const ProcessedImage = IDL.Record({
  'id' : IDL.Nat,
  'optimizedUrl' : IDL.Opt(IDL.Text),
  'originalWidth' : IDL.Opt(IDL.Nat),
  'imageType' : ImageType,
  'originalHeight' : IDL.Opt(IDL.Nat),
  'sortOrder' : IDL.Nat,
  'fileSizeBytes' : IDL.Nat,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'uploadTime' : Time,
  'aspectRatio' : AspectRatioOption,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : ServiceCategory,
  'image' : IDL.Opt(ProcessedImage),
  'price' : IDL.Nat,
});
export const StoreSubcategoryService = IDL.Record({
  'id' : IDL.Nat,
  'subcategory' : StoreServiceCategory,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'image' : IDL.Opt(ProcessedImage),
  'price' : IDL.Nat,
});
export const ContactFormEntry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const PatternType = IDL.Variant({
  'waterRipples' : IDL.Null,
  'bubbles' : IDL.Null,
  'fabricTexture' : IDL.Null,
});
export const BackgroundTheme = IDL.Record({
  'pattern' : PatternType,
  'baseColor' : IDL.Text,
  'patternIntensity' : IDL.Nat,
  'transparencyLevel' : IDL.Nat,
});
export const BannerInfo = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const GradientConfig = IDL.Record({
  'direction' : IDL.Text,
  'endColor' : IDL.Text,
  'startColor' : IDL.Text,
  'intensity' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const ColorHarmony = IDL.Record({
  'accent' : IDL.Text,
  'secondary' : IDL.Text,
  'primary' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'hours' : IDL.Text,
  'whatsapp' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ThemeConfig = IDL.Record({
  'harmonyLevel' : IDL.Nat,
  'luxuryPreset' : IDL.Bool,
  'colorHarmony' : ColorHarmony,
  'gradients' : IDL.Vec(GradientConfig),
});
export const ShadowConfig = IDL.Record({
  'blurRadius' : IDL.Nat,
  'color' : IDL.Text,
  'offsetX' : IDL.Int,
  'offsetY' : IDL.Int,
});
export const LayoutConfig = IDL.Record({
  'borderRadius' : IDL.Nat,
  'margin' : IDL.Nat,
  'padding' : IDL.Nat,
  'alignment' : IDL.Text,
});
export const TextureConfig = IDL.Record({
  'patternType' : IDL.Text,
  'scale' : IDL.Nat,
  'colorOverlay' : IDL.Text,
  'intensity' : IDL.Nat,
});
export const ResponsiveConfig = IDL.Record({
  'mobileFontSize' : IDL.Nat,
  'desktopPadding' : IDL.Nat,
  'tabletFontSize' : IDL.Nat,
  'desktopFontSize' : IDL.Nat,
  'mobilePadding' : IDL.Nat,
  'tabletPadding' : IDL.Nat,
});
export const TypographyConfig = IDL.Record({
  'fontFamily' : IDL.Text,
  'fontWeight' : IDL.Text,
  'fontSize' : IDL.Nat,
  'letterSpacing' : IDL.Nat,
});
export const HeaderStyleConfig = IDL.Record({
  'shadow' : IDL.Opt(ShadowConfig),
  'gradient' : IDL.Opt(GradientConfig),
  'layout' : IDL.Opt(LayoutConfig),
  'isResponsive' : IDL.Bool,
  'texture' : IDL.Opt(TextureConfig),
  'responsive' : IDL.Opt(ResponsiveConfig),
  'colorHarmony' : IDL.Opt(ColorHarmony),
  'typography' : IDL.Opt(TypographyConfig),
});
export const ExtendedThemeConfig = IDL.Record({
  'harmonyLevel' : IDL.Nat,
  'theme' : IDL.Opt(ThemeConfig),
  'gradient' : IDL.Opt(GradientConfig),
  'luxuryPreset' : IDL.Bool,
  'headerStyle' : IDL.Opt(HeaderStyleConfig),
  'colorHarmony' : IDL.Opt(ColorHarmony),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ServiceCategory],
      [IDL.Nat],
      [],
    ),
  'createStoreSubcategoryService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, StoreServiceCategory],
      [IDL.Nat],
      [],
    ),
  'deleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'deleteStoreSubcategoryService' : IDL.Func([IDL.Nat], [], []),
  'getAllActiveServicesByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getAllActiveStoreSubcategoryServicesBySubcategory' : IDL.Func(
      [StoreServiceCategory],
      [IDL.Vec(StoreSubcategoryService)],
      ['query'],
    ),
  'getAllContactFormEntries' : IDL.Func(
      [],
      [IDL.Vec(ContactFormEntry)],
      ['query'],
    ),
  'getAllCustomerPhotoIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getAllProcessedImages' : IDL.Func([], [IDL.Vec(ProcessedImage)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllStoreSubcategoryServices' : IDL.Func(
      [],
      [IDL.Vec(StoreSubcategoryService)],
      ['query'],
    ),
  'getBackgroundTheme' : IDL.Func([], [BackgroundTheme], ['query']),
  'getBanner' : IDL.Func([], [IDL.Opt(BannerInfo)], ['query']),
  'getButtonGradient' : IDL.Func([], [GradientConfig], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getColorHarmony' : IDL.Func([], [IDL.Opt(ColorHarmony)], ['query']),
  'getContactFormEntry' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ContactFormEntry)],
      ['query'],
    ),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getCustomerPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
  'getExtendedThemeConfig' : IDL.Func(
      [],
      [IDL.Opt(ExtendedThemeConfig)],
      ['query'],
    ),
  'getGradients' : IDL.Func([], [IDL.Vec(GradientConfig)], ['query']),
  'getHeaderStyleConfig' : IDL.Func(
      [],
      [IDL.Opt(HeaderStyleConfig)],
      ['query'],
    ),
  'getImagesByType' : IDL.Func(
      [ImageType],
      [IDL.Vec(ProcessedImage)],
      ['query'],
    ),
  'getInStoreSubcategoriesCount' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getOrderedGalleryImages' : IDL.Func(
      [],
      [IDL.Vec(ProcessedImage)],
      ['query'],
    ),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getServicesByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getServicesByStoreSubcategory' : IDL.Func(
      [StoreServiceCategory],
      [IDL.Vec(StoreSubcategoryService)],
      ['query'],
    ),
  'getStaticDescription' : IDL.Func([], [IDL.Text], ['query']),
  'getStoreSubcategoryService' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(StoreSubcategoryService)],
      ['query'],
    ),
  'getThemeConfig' : IDL.Func([], [IDL.Opt(ThemeConfig)], ['query']),
  'getTitleGradient' : IDL.Func([], [GradientConfig], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isDemoModeActive' : IDL.Func([], [IDL.Bool], ['query']),
  'isDemoStateSet' : IDL.Func([], [IDL.Bool], ['query']),
  'replaceGalleryImage' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
        AspectRatioOption,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBackgroundTheme' : IDL.Func([BackgroundTheme], [], []),
  'setDemoState' : IDL.Func([], [], []),
  'setExtendedThemeConfig' : IDL.Func([ExtendedThemeConfig], [], []),
  'setHeaderStyleConfig' : IDL.Func([HeaderStyleConfig], [], []),
  'setThemeConfig' : IDL.Func([ThemeConfig], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateContactInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateImageDescription' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateServiceWithoutImage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateStoreSubcategoryService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateStoreSubcategoryServiceWithoutImage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'uploadBanner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'uploadCustomerPhoto' : IDL.Func([ExternalBlob], [IDL.Nat], []),
  'uploadHeroImage' : IDL.Func(
      [
        IDL.Opt(ExternalBlob),
        IDL.Text,
        AspectRatioOption,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'uploadLogoImage' : IDL.Func(
      [
        IDL.Opt(ExternalBlob),
        IDL.Text,
        AspectRatioOption,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'uploadProcessedContactBackgroundImage' : IDL.Func(
      [
        IDL.Opt(ExternalBlob),
        IDL.Text,
        AspectRatioOption,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'uploadProcessedGalleryImage' : IDL.Func(
      [
        IDL.Opt(ExternalBlob),
        IDL.Text,
        AspectRatioOption,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'uploadProcessedServiceImage' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(ExternalBlob),
        AspectRatioOption,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'uploadProcessedStoreSubcategoryServiceImage' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(ExternalBlob),
        AspectRatioOption,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceCategory = IDL.Variant({
    'inStore' : IDL.Null,
    'online' : IDL.Null,
  });
  const StoreServiceCategory = IDL.Variant({
    'operatorService' : IDL.Null,
    'selfService' : IDL.Null,
  });
  const ImageType = IDL.Variant({
    'service' : IDL.Null,
    'hero' : IDL.Null,
    'logo' : IDL.Null,
    'contactBackground' : IDL.Null,
    'gallery' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const AspectRatioOption = IDL.Variant({
    'square' : IDL.Null,
    'portrait' : IDL.Null,
    'original' : IDL.Null,
    'landscape' : IDL.Null,
  });
  const ProcessedImage = IDL.Record({
    'id' : IDL.Nat,
    'optimizedUrl' : IDL.Opt(IDL.Text),
    'originalWidth' : IDL.Opt(IDL.Nat),
    'imageType' : ImageType,
    'originalHeight' : IDL.Opt(IDL.Nat),
    'sortOrder' : IDL.Nat,
    'fileSizeBytes' : IDL.Nat,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'uploadTime' : Time,
    'aspectRatio' : AspectRatioOption,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : ServiceCategory,
    'image' : IDL.Opt(ProcessedImage),
    'price' : IDL.Nat,
  });
  const StoreSubcategoryService = IDL.Record({
    'id' : IDL.Nat,
    'subcategory' : StoreServiceCategory,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'image' : IDL.Opt(ProcessedImage),
    'price' : IDL.Nat,
  });
  const ContactFormEntry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const PatternType = IDL.Variant({
    'waterRipples' : IDL.Null,
    'bubbles' : IDL.Null,
    'fabricTexture' : IDL.Null,
  });
  const BackgroundTheme = IDL.Record({
    'pattern' : PatternType,
    'baseColor' : IDL.Text,
    'patternIntensity' : IDL.Nat,
    'transparencyLevel' : IDL.Nat,
  });
  const BannerInfo = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const GradientConfig = IDL.Record({
    'direction' : IDL.Text,
    'endColor' : IDL.Text,
    'startColor' : IDL.Text,
    'intensity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const ColorHarmony = IDL.Record({
    'accent' : IDL.Text,
    'secondary' : IDL.Text,
    'primary' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'hours' : IDL.Text,
    'whatsapp' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ThemeConfig = IDL.Record({
    'harmonyLevel' : IDL.Nat,
    'luxuryPreset' : IDL.Bool,
    'colorHarmony' : ColorHarmony,
    'gradients' : IDL.Vec(GradientConfig),
  });
  const ShadowConfig = IDL.Record({
    'blurRadius' : IDL.Nat,
    'color' : IDL.Text,
    'offsetX' : IDL.Int,
    'offsetY' : IDL.Int,
  });
  const LayoutConfig = IDL.Record({
    'borderRadius' : IDL.Nat,
    'margin' : IDL.Nat,
    'padding' : IDL.Nat,
    'alignment' : IDL.Text,
  });
  const TextureConfig = IDL.Record({
    'patternType' : IDL.Text,
    'scale' : IDL.Nat,
    'colorOverlay' : IDL.Text,
    'intensity' : IDL.Nat,
  });
  const ResponsiveConfig = IDL.Record({
    'mobileFontSize' : IDL.Nat,
    'desktopPadding' : IDL.Nat,
    'tabletFontSize' : IDL.Nat,
    'desktopFontSize' : IDL.Nat,
    'mobilePadding' : IDL.Nat,
    'tabletPadding' : IDL.Nat,
  });
  const TypographyConfig = IDL.Record({
    'fontFamily' : IDL.Text,
    'fontWeight' : IDL.Text,
    'fontSize' : IDL.Nat,
    'letterSpacing' : IDL.Nat,
  });
  const HeaderStyleConfig = IDL.Record({
    'shadow' : IDL.Opt(ShadowConfig),
    'gradient' : IDL.Opt(GradientConfig),
    'layout' : IDL.Opt(LayoutConfig),
    'isResponsive' : IDL.Bool,
    'texture' : IDL.Opt(TextureConfig),
    'responsive' : IDL.Opt(ResponsiveConfig),
    'colorHarmony' : IDL.Opt(ColorHarmony),
    'typography' : IDL.Opt(TypographyConfig),
  });
  const ExtendedThemeConfig = IDL.Record({
    'harmonyLevel' : IDL.Nat,
    'theme' : IDL.Opt(ThemeConfig),
    'gradient' : IDL.Opt(GradientConfig),
    'luxuryPreset' : IDL.Bool,
    'headerStyle' : IDL.Opt(HeaderStyleConfig),
    'colorHarmony' : IDL.Opt(ColorHarmony),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ServiceCategory],
        [IDL.Nat],
        [],
      ),
    'createStoreSubcategoryService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, StoreServiceCategory],
        [IDL.Nat],
        [],
      ),
    'deleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'deleteStoreSubcategoryService' : IDL.Func([IDL.Nat], [], []),
    'getAllActiveServicesByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getAllActiveStoreSubcategoryServicesBySubcategory' : IDL.Func(
        [StoreServiceCategory],
        [IDL.Vec(StoreSubcategoryService)],
        ['query'],
      ),
    'getAllContactFormEntries' : IDL.Func(
        [],
        [IDL.Vec(ContactFormEntry)],
        ['query'],
      ),
    'getAllCustomerPhotoIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getAllProcessedImages' : IDL.Func(
        [],
        [IDL.Vec(ProcessedImage)],
        ['query'],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllStoreSubcategoryServices' : IDL.Func(
        [],
        [IDL.Vec(StoreSubcategoryService)],
        ['query'],
      ),
    'getBackgroundTheme' : IDL.Func([], [BackgroundTheme], ['query']),
    'getBanner' : IDL.Func([], [IDL.Opt(BannerInfo)], ['query']),
    'getButtonGradient' : IDL.Func([], [GradientConfig], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getColorHarmony' : IDL.Func([], [IDL.Opt(ColorHarmony)], ['query']),
    'getContactFormEntry' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ContactFormEntry)],
        ['query'],
      ),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getCustomerPhoto' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getExtendedThemeConfig' : IDL.Func(
        [],
        [IDL.Opt(ExtendedThemeConfig)],
        ['query'],
      ),
    'getGradients' : IDL.Func([], [IDL.Vec(GradientConfig)], ['query']),
    'getHeaderStyleConfig' : IDL.Func(
        [],
        [IDL.Opt(HeaderStyleConfig)],
        ['query'],
      ),
    'getImagesByType' : IDL.Func(
        [ImageType],
        [IDL.Vec(ProcessedImage)],
        ['query'],
      ),
    'getInStoreSubcategoriesCount' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getOrderedGalleryImages' : IDL.Func(
        [],
        [IDL.Vec(ProcessedImage)],
        ['query'],
      ),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getServicesByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getServicesByStoreSubcategory' : IDL.Func(
        [StoreServiceCategory],
        [IDL.Vec(StoreSubcategoryService)],
        ['query'],
      ),
    'getStaticDescription' : IDL.Func([], [IDL.Text], ['query']),
    'getStoreSubcategoryService' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(StoreSubcategoryService)],
        ['query'],
      ),
    'getThemeConfig' : IDL.Func([], [IDL.Opt(ThemeConfig)], ['query']),
    'getTitleGradient' : IDL.Func([], [GradientConfig], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isDemoModeActive' : IDL.Func([], [IDL.Bool], ['query']),
    'isDemoStateSet' : IDL.Func([], [IDL.Bool], ['query']),
    'replaceGalleryImage' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
          AspectRatioOption,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBackgroundTheme' : IDL.Func([BackgroundTheme], [], []),
    'setDemoState' : IDL.Func([], [], []),
    'setExtendedThemeConfig' : IDL.Func([ExtendedThemeConfig], [], []),
    'setHeaderStyleConfig' : IDL.Func([HeaderStyleConfig], [], []),
    'setThemeConfig' : IDL.Func([ThemeConfig], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateImageDescription' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateServiceWithoutImage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateStoreSubcategoryService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateStoreSubcategoryServiceWithoutImage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'uploadBanner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'uploadCustomerPhoto' : IDL.Func([ExternalBlob], [IDL.Nat], []),
    'uploadHeroImage' : IDL.Func(
        [
          IDL.Opt(ExternalBlob),
          IDL.Text,
          AspectRatioOption,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'uploadLogoImage' : IDL.Func(
        [
          IDL.Opt(ExternalBlob),
          IDL.Text,
          AspectRatioOption,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'uploadProcessedContactBackgroundImage' : IDL.Func(
        [
          IDL.Opt(ExternalBlob),
          IDL.Text,
          AspectRatioOption,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'uploadProcessedGalleryImage' : IDL.Func(
        [
          IDL.Opt(ExternalBlob),
          IDL.Text,
          AspectRatioOption,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'uploadProcessedServiceImage' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(ExternalBlob),
          AspectRatioOption,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'uploadProcessedStoreSubcategoryServiceImage' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(ExternalBlob),
          AspectRatioOption,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };