/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AspectRatioOption = { 'square' : null } |
  { 'portrait' : null } |
  { 'original' : null } |
  { 'landscape' : null };
export interface BackgroundTheme {
  'pattern' : PatternType,
  'baseColor' : string,
  'patternIntensity' : bigint,
  'transparencyLevel' : bigint,
}
export interface BannerInfo {
  'name' : string,
  'message' : string,
  'image' : [] | [ExternalBlob],
}
export interface ColorHarmony {
  'accent' : string,
  'secondary' : string,
  'primary' : string,
}
export interface ContactFormEntry {
  'id' : bigint,
  'name' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface ContactInfo {
  'hours' : string,
  'whatsapp' : string,
  'address' : string,
  'phone' : string,
}
export interface ExtendedThemeConfig {
  'harmonyLevel' : bigint,
  'theme' : [] | [ThemeConfig],
  'gradient' : [] | [GradientConfig],
  'luxuryPreset' : boolean,
  'headerStyle' : [] | [HeaderStyleConfig],
  'colorHarmony' : [] | [ColorHarmony],
}
export type ExternalBlob = Uint8Array;
export interface GradientConfig {
  'direction' : string,
  'endColor' : string,
  'startColor' : string,
  'intensity' : bigint,
}
export interface HeaderStyleConfig {
  'shadow' : [] | [ShadowConfig],
  'gradient' : [] | [GradientConfig],
  'layout' : [] | [LayoutConfig],
  'isResponsive' : boolean,
  'texture' : [] | [TextureConfig],
  'responsive' : [] | [ResponsiveConfig],
  'colorHarmony' : [] | [ColorHarmony],
  'typography' : [] | [TypographyConfig],
}
export type ImageType = { 'service' : null } |
  { 'hero' : null } |
  { 'logo' : null } |
  { 'photoBackground' : null } |
  { 'contactBackground' : null } |
  { 'gallery' : null };
export interface LayoutConfig {
  'borderRadius' : bigint,
  'margin' : bigint,
  'padding' : bigint,
  'alignment' : string,
}
export type PatternType = { 'waterRipples' : null } |
  { 'bubbles' : null } |
  { 'fabricTexture' : null };
export interface ProcessedImage {
  'id' : bigint,
  'optimizedUrl' : [] | [string],
  'originalWidth' : [] | [bigint],
  'imageType' : ImageType,
  'originalHeight' : [] | [bigint],
  'sortOrder' : bigint,
  'fileSizeBytes' : bigint,
  'description' : string,
  'image' : [] | [ExternalBlob],
  'uploadTime' : Time,
  'aspectRatio' : AspectRatioOption,
}
export interface ResponsiveConfig {
  'mobileFontSize' : bigint,
  'desktopPadding' : bigint,
  'tabletFontSize' : bigint,
  'desktopFontSize' : bigint,
  'mobilePadding' : bigint,
  'tabletPadding' : bigint,
}
export interface Service {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : ServiceCategory,
  'image' : [] | [ProcessedImage],
  'price' : bigint,
}
export type ServiceCategory = { 'inStore' : null } |
  { 'online' : null };
export interface ShadowConfig {
  'blurRadius' : bigint,
  'color' : string,
  'offsetX' : bigint,
  'offsetY' : bigint,
}
export type StoreServiceCategory = { 'operatorService' : null } |
  { 'selfService' : null };
export interface StoreSubcategoryService {
  'id' : bigint,
  'subcategory' : StoreServiceCategory,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'image' : [] | [ProcessedImage],
  'price' : bigint,
}
export interface TextureConfig {
  'patternType' : string,
  'scale' : bigint,
  'colorOverlay' : string,
  'intensity' : bigint,
}
export interface ThemeConfig {
  'harmonyLevel' : bigint,
  'luxuryPreset' : boolean,
  'colorHarmony' : ColorHarmony,
  'gradients' : Array<GradientConfig>,
}
export type Time = bigint;
export interface TypographyConfig {
  'fontFamily' : string,
  'fontWeight' : string,
  'fontSize' : bigint,
  'letterSpacing' : bigint,
}
export interface UserProfile { 'name' : string, 'phoneNumber' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createService' : ActorMethod<
    [string, string, bigint, ServiceCategory],
    bigint
  >,
  'createStoreSubcategoryService' : ActorMethod<
    [string, string, bigint, StoreServiceCategory],
    bigint
  >,
  'deleteGalleryImage' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'deleteStoreSubcategoryService' : ActorMethod<[bigint], undefined>,
  'getAllActiveServicesByCategory' : ActorMethod<
    [ServiceCategory],
    Array<Service>
  >,
  'getAllActiveStoreSubcategoryServicesBySubcategory' : ActorMethod<
    [StoreServiceCategory],
    Array<StoreSubcategoryService>
  >,
  'getAllContactFormEntries' : ActorMethod<[], Array<ContactFormEntry>>,
  'getAllCustomerPhotoIds' : ActorMethod<[], Array<bigint>>,
  'getAllProcessedImages' : ActorMethod<[], Array<ProcessedImage>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllStoreSubcategoryServices' : ActorMethod<
    [],
    Array<StoreSubcategoryService>
  >,
  'getBackgroundTheme' : ActorMethod<[], BackgroundTheme>,
  'getBanner' : ActorMethod<[], [] | [BannerInfo]>,
  'getButtonGradient' : ActorMethod<[], GradientConfig>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getColorHarmony' : ActorMethod<[], [] | [ColorHarmony]>,
  'getContactFormEntry' : ActorMethod<[bigint], [] | [ContactFormEntry]>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getCustomerPhoto' : ActorMethod<[bigint], [] | [ExternalBlob]>,
  'getCustomerPhotos' : ActorMethod<[], Array<ExternalBlob>>,
  'getExtendedThemeConfig' : ActorMethod<[], [] | [ExtendedThemeConfig]>,
  'getGradients' : ActorMethod<[], Array<GradientConfig>>,
  'getHeaderStyleConfig' : ActorMethod<[], [] | [HeaderStyleConfig]>,
  'getImagesByType' : ActorMethod<[ImageType], Array<ProcessedImage>>,
  'getInStoreSubcategoriesCount' : ActorMethod<[], [bigint, bigint]>,
  'getOrderedGalleryImages' : ActorMethod<[], Array<ProcessedImage>>,
  'getPhotoBackgroundImage' : ActorMethod<[], [] | [ExternalBlob]>,
  'getQrCodeCaption' : ActorMethod<[], string>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getServicesByCategory' : ActorMethod<[ServiceCategory], Array<Service>>,
  'getServicesByStoreSubcategory' : ActorMethod<
    [StoreServiceCategory],
    Array<StoreSubcategoryService>
  >,
  'getStaticDescription' : ActorMethod<[], string>,
  'getStoreSubcategoryService' : ActorMethod<
    [bigint],
    [] | [StoreSubcategoryService]
  >,
  'getThemeConfig' : ActorMethod<[], [] | [ThemeConfig]>,
  'getTitleGradient' : ActorMethod<[], GradientConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isDemoModeActive' : ActorMethod<[], boolean>,
  'isDemoStateSet' : ActorMethod<[], boolean>,
  'removePhotoBackgroundImage' : ActorMethod<[], undefined>,
  'replaceGalleryImage' : ActorMethod<
    [
      bigint,
      [] | [ExternalBlob],
      [] | [string],
      AspectRatioOption,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBackgroundTheme' : ActorMethod<[BackgroundTheme], undefined>,
  'setDemoState' : ActorMethod<[], undefined>,
  'setExtendedThemeConfig' : ActorMethod<[ExtendedThemeConfig], undefined>,
  'setHeaderStyleConfig' : ActorMethod<[HeaderStyleConfig], undefined>,
  'setQrCodeCaption' : ActorMethod<[string], undefined>,
  'setThemeConfig' : ActorMethod<[ThemeConfig], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'updateContactInfo' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateImageDescription' : ActorMethod<[bigint, string], undefined>,
  'updateService' : ActorMethod<[bigint, string, string, bigint], undefined>,
  'updateServiceWithoutImage' : ActorMethod<
    [bigint, string, string, bigint],
    undefined
  >,
  'updateStoreSubcategoryService' : ActorMethod<
    [bigint, string, string, bigint],
    undefined
  >,
  'updateStoreSubcategoryServiceWithoutImage' : ActorMethod<
    [bigint, string, string, bigint],
    undefined
  >,
  'uploadBanner' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
  'uploadCustomerPhoto' : ActorMethod<[ExternalBlob], bigint>,
  'uploadGalleryImage' : ActorMethod<
    [
      [] | [ExternalBlob],
      string,
      AspectRatioOption,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    bigint
  >,
  'uploadHeroImage' : ActorMethod<
    [
      [] | [ExternalBlob],
      string,
      AspectRatioOption,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    bigint
  >,
  'uploadLogoImage' : ActorMethod<
    [
      [] | [ExternalBlob],
      string,
      AspectRatioOption,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    bigint
  >,
  'uploadPhotoBackgroundImage' : ActorMethod<[ExternalBlob], undefined>,
  'uploadProcessedContactBackgroundImage' : ActorMethod<
    [
      [] | [ExternalBlob],
      string,
      AspectRatioOption,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    bigint
  >,
  'uploadProcessedGalleryImage' : ActorMethod<
    [
      [] | [ExternalBlob],
      string,
      AspectRatioOption,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    bigint
  >,
  'uploadProcessedServiceImage' : ActorMethod<
    [
      bigint,
      [] | [ExternalBlob],
      AspectRatioOption,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
  'uploadProcessedStoreSubcategoryServiceImage' : ActorMethod<
    [
      bigint,
      [] | [ExternalBlob],
      AspectRatioOption,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
  'uploadServiceImage' : ActorMethod<
    [
      bigint,
      [] | [ExternalBlob],
      AspectRatioOption,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
  'uploadStoreSubcategoryServiceImage' : ActorMethod<
    [
      bigint,
      [] | [ExternalBlob],
      AspectRatioOption,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];