/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShadowConfig {
    blurRadius: bigint;
    color: string;
    offsetX: bigint;
    offsetY: bigint;
}
export interface ProcessedImage {
    id: bigint;
    optimizedUrl?: string;
    originalWidth?: bigint;
    imageType: ImageType;
    originalHeight?: bigint;
    sortOrder: bigint;
    fileSizeBytes: bigint;
    description: string;
    image?: ExternalBlob;
    uploadTime: Time;
    aspectRatio: AspectRatioOption;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TextureConfig {
    patternType: string;
    scale: bigint;
    colorOverlay: string;
    intensity: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ColorHarmony {
    accent: string;
    secondary: string;
    primary: string;
}
export interface HeaderStyleConfig {
    shadow?: ShadowConfig;
    gradient?: GradientConfig;
    layout?: LayoutConfig;
    isResponsive: boolean;
    texture?: TextureConfig;
    responsive?: ResponsiveConfig;
    colorHarmony?: ColorHarmony;
    typography?: TypographyConfig;
}
export interface GradientConfig {
    direction: string;
    endColor: string;
    startColor: string;
    intensity: bigint;
}
export interface TypographyConfig {
    fontFamily: string;
    fontWeight: string;
    fontSize: bigint;
    letterSpacing: bigint;
}
export interface ContactInfo {
    hours: string;
    whatsapp: string;
    address: string;
    phone: string;
}
export interface ContactFormEntry {
    id: bigint;
    name: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export interface BannerInfo {
    name: string;
    message: string;
    image?: ExternalBlob;
}
export interface ResponsiveConfig {
    mobileFontSize: bigint;
    desktopPadding: bigint;
    tabletFontSize: bigint;
    desktopFontSize: bigint;
    mobilePadding: bigint;
    tabletPadding: bigint;
}
export interface Service {
    id: bigint;
    name: string;
    description: string;
    isActive: boolean;
    category: ServiceCategory;
    image?: ProcessedImage;
    price: bigint;
}
export interface ThemeConfig {
    harmonyLevel: bigint;
    luxuryPreset: boolean;
    colorHarmony: ColorHarmony;
    gradients: Array<GradientConfig>;
}
export interface StoreSubcategoryService {
    id: bigint;
    subcategory: StoreServiceCategory;
    name: string;
    description: string;
    isActive: boolean;
    image?: ProcessedImage;
    price: bigint;
}
export interface LayoutConfig {
    borderRadius: bigint;
    margin: bigint;
    padding: bigint;
    alignment: string;
}
export interface ExtendedThemeConfig {
    harmonyLevel: bigint;
    theme?: ThemeConfig;
    gradient?: GradientConfig;
    luxuryPreset: boolean;
    headerStyle?: HeaderStyleConfig;
    colorHarmony?: ColorHarmony;
}
export interface BackgroundTheme {
    pattern: PatternType;
    baseColor: string;
    patternIntensity: bigint;
    transparencyLevel: bigint;
}
export interface UserProfile {
    name: string;
    phoneNumber: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AspectRatioOption {
    square = "square",
    portrait = "portrait",
    original = "original",
    landscape = "landscape"
}
export enum ImageType {
    service = "service",
    hero = "hero",
    logo = "logo",
    photoBackground = "photoBackground",
    contactBackground = "contactBackground",
    gallery = "gallery"
}
export enum PatternType {
    waterRipples = "waterRipples",
    bubbles = "bubbles",
    fabricTexture = "fabricTexture"
}
export enum ServiceCategory {
    inStore = "inStore",
    online = "online"
}
export enum StoreServiceCategory {
    operatorService = "operatorService",
    selfService = "selfService"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createService(name: string, description: string, price: bigint, category: ServiceCategory): Promise<bigint>;
    createStoreSubcategoryService(name: string, description: string, price: bigint, subcategory: StoreServiceCategory): Promise<bigint>;
    deleteGalleryImage(imageId: bigint): Promise<void>;
    deleteService(id: bigint): Promise<void>;
    deleteStoreSubcategoryService(id: bigint): Promise<void>;
    getAllActiveServicesByCategory(category: ServiceCategory): Promise<Array<Service>>;
    getAllActiveStoreSubcategoryServicesBySubcategory(subcategory: StoreServiceCategory): Promise<Array<StoreSubcategoryService>>;
    getAllContactFormEntries(): Promise<Array<ContactFormEntry>>;
    /**
     * / Admin-only access to list customer photo IDs for privacy protection
     */
    getAllCustomerPhotoIds(): Promise<Array<bigint>>;
    getAllProcessedImages(): Promise<Array<ProcessedImage>>;
    getAllServices(): Promise<Array<Service>>;
    getAllStoreSubcategoryServices(): Promise<Array<StoreSubcategoryService>>;
    getBackgroundTheme(): Promise<BackgroundTheme>;
    getBanner(): Promise<BannerInfo | null>;
    getButtonGradient(): Promise<GradientConfig>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getColorHarmony(): Promise<ColorHarmony | null>;
    getContactFormEntry(id: bigint): Promise<ContactFormEntry | null>;
    getContactInfo(): Promise<ContactInfo>;
    /**
     * / Admin-only access to view customer photos for privacy protection
     */
    getCustomerPhoto(id: bigint): Promise<ExternalBlob | null>;
    getExtendedThemeConfig(): Promise<ExtendedThemeConfig | null>;
    getGradients(): Promise<Array<GradientConfig>>;
    getHeaderStyleConfig(): Promise<HeaderStyleConfig | null>;
    getImagesByType(imageType: ImageType): Promise<Array<ProcessedImage>>;
    getInStoreSubcategoriesCount(): Promise<[bigint, bigint]>;
    getOrderedGalleryImages(): Promise<Array<ProcessedImage>>;
    getPhotoBackgroundImage(): Promise<ExternalBlob | null>;
    getService(id: bigint): Promise<Service | null>;
    getServicesByCategory(category: ServiceCategory): Promise<Array<Service>>;
    getServicesByStoreSubcategory(subcategory: StoreServiceCategory): Promise<Array<StoreSubcategoryService>>;
    getStaticDescription(): Promise<string>;
    getStoreSubcategoryService(id: bigint): Promise<StoreSubcategoryService | null>;
    getThemeConfig(): Promise<ThemeConfig | null>;
    getTitleGradient(): Promise<GradientConfig>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isDemoModeActive(): Promise<boolean>;
    isDemoStateSet(): Promise<boolean>;
    removePhotoBackgroundImage(): Promise<void>;
    replaceGalleryImage(imageId: bigint, newImage: ExternalBlob | null, desc: string | null, aspectRatio: AspectRatioOption, fileSizeBytes: bigint, optimizedUrl: string | null, width: bigint | null, height: bigint | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setBackgroundTheme(bgTheme: BackgroundTheme): Promise<void>;
    setDemoState(): Promise<void>;
    setExtendedThemeConfig(config: ExtendedThemeConfig): Promise<void>;
    setHeaderStyleConfig(config: HeaderStyleConfig): Promise<void>;
    setThemeConfig(config: ThemeConfig): Promise<void>;
    submitContactForm(name: string, phone: string, message: string): Promise<bigint>;
    updateContactInfo(phone: string, whatsapp: string, address: string, hours: string): Promise<void>;
    updateImageDescription(id: bigint, newDesc: string): Promise<void>;
    updateService(id: bigint, name: string, description: string, price: bigint): Promise<void>;
    updateServiceWithoutImage(id: bigint, name: string, description: string, price: bigint): Promise<void>;
    updateStoreSubcategoryService(id: bigint, name: string, description: string, price: bigint): Promise<void>;
    updateStoreSubcategoryServiceWithoutImage(id: bigint, name: string, description: string, price: bigint): Promise<void>;
    uploadBanner(name: string, message: string, image: ExternalBlob | null): Promise<void>;
    /**
     * / PUBLIC API FOR CUSTOMER PHOTOS (Shared with #anon)
     */
    uploadCustomerPhoto(photo: ExternalBlob): Promise<bigint>;
    uploadHeroImage(image: ExternalBlob | null, desc: string, aspectRatio: AspectRatioOption, fileSizeBytes: bigint, optimizedUrl: string | null, width: bigint | null, height: bigint | null): Promise<bigint>;
    uploadLogoImage(image: ExternalBlob | null, desc: string, aspectRatio: AspectRatioOption, fileSizeBytes: bigint, optimizedUrl: string | null, width: bigint | null, height: bigint | null): Promise<bigint>;
    uploadPhotoBackgroundImage(blob: ExternalBlob): Promise<void>;
    uploadProcessedContactBackgroundImage(image: ExternalBlob | null, desc: string, aspectRatio: AspectRatioOption, fileSizeBytes: bigint, optimizedUrl: string | null, width: bigint | null, height: bigint | null): Promise<bigint>;
    uploadProcessedGalleryImage(image: ExternalBlob | null, desc: string, aspectRatio: AspectRatioOption, fileSizeBytes: bigint, optimizedUrl: string | null, width: bigint | null, height: bigint | null): Promise<bigint>;
    uploadProcessedServiceImage(id: bigint, image: ExternalBlob | null, aspectRatio: AspectRatioOption, fileSizeBytes: bigint, optimizedUrl: string | null, width: bigint | null, height: bigint | null): Promise<void>;
    uploadProcessedStoreSubcategoryServiceImage(id: bigint, image: ExternalBlob | null, aspectRatio: AspectRatioOption, fileSizeBytes: bigint, optimizedUrl: string | null, width: bigint | null, height: bigint | null): Promise<void>;
}
import type { AspectRatioOption as _AspectRatioOption, BackgroundTheme as _BackgroundTheme, BannerInfo as _BannerInfo, ColorHarmony as _ColorHarmony, ContactFormEntry as _ContactFormEntry, ExtendedThemeConfig as _ExtendedThemeConfig, ExternalBlob as _ExternalBlob, GradientConfig as _GradientConfig, HeaderStyleConfig as _HeaderStyleConfig, ImageType as _ImageType, LayoutConfig as _LayoutConfig, PatternType as _PatternType, ProcessedImage as _ProcessedImage, ResponsiveConfig as _ResponsiveConfig, Service as _Service, ServiceCategory as _ServiceCategory, ShadowConfig as _ShadowConfig, StoreServiceCategory as _StoreServiceCategory, StoreSubcategoryService as _StoreSubcategoryService, TextureConfig as _TextureConfig, ThemeConfig as _ThemeConfig, Time as _Time, TypographyConfig as _TypographyConfig, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createService(arg0: string, arg1: string, arg2: bigint, arg3: ServiceCategory): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(arg0, arg1, arg2, to_candid_ServiceCategory_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(arg0, arg1, arg2, to_candid_ServiceCategory_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createStoreSubcategoryService(arg0: string, arg1: string, arg2: bigint, arg3: StoreServiceCategory): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStoreSubcategoryService(arg0, arg1, arg2, to_candid_StoreServiceCategory_n12(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStoreSubcategoryService(arg0, arg1, arg2, to_candid_StoreServiceCategory_n12(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteGalleryImage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deleteService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async deleteStoreSubcategoryService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStoreSubcategoryService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStoreSubcategoryService(arg0);
            return result;
        }
    }
    async getAllActiveServicesByCategory(arg0: ServiceCategory): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveServicesByCategory(to_candid_ServiceCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveServicesByCategory(to_candid_ServiceCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveStoreSubcategoryServicesBySubcategory(arg0: StoreServiceCategory): Promise<Array<StoreSubcategoryService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveStoreSubcategoryServicesBySubcategory(to_candid_StoreServiceCategory_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveStoreSubcategoryServicesBySubcategory(to_candid_StoreServiceCategory_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactFormEntries(): Promise<Array<ContactFormEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactFormEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactFormEntries();
            return result;
        }
    }
    async getAllCustomerPhotoIds(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomerPhotoIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomerPhotoIds();
            return result;
        }
    }
    async getAllProcessedImages(): Promise<Array<ProcessedImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProcessedImages();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProcessedImages();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStoreSubcategoryServices(): Promise<Array<StoreSubcategoryService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStoreSubcategoryServices();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStoreSubcategoryServices();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBackgroundTheme(): Promise<BackgroundTheme> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackgroundTheme();
                return from_candid_BackgroundTheme_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackgroundTheme();
            return from_candid_BackgroundTheme_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBanner(): Promise<BannerInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBanner();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBanner();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getButtonGradient(): Promise<GradientConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getButtonGradient();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getButtonGradient();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getColorHarmony(): Promise<ColorHarmony | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getColorHarmony();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColorHarmony();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactFormEntry(arg0: bigint): Promise<ContactFormEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactFormEntry(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactFormEntry(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInfo(): Promise<ContactInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return result;
        }
    }
    async getCustomerPhoto(arg0: bigint): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerPhoto(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerPhoto(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExtendedThemeConfig(): Promise<ExtendedThemeConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExtendedThemeConfig();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExtendedThemeConfig();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGradients(): Promise<Array<GradientConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGradients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGradients();
            return result;
        }
    }
    async getHeaderStyleConfig(): Promise<HeaderStyleConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeaderStyleConfig();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeaderStyleConfig();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImagesByType(arg0: ImageType): Promise<Array<ProcessedImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImagesByType(to_candid_ImageType_n60(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImagesByType(to_candid_ImageType_n60(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInStoreSubcategoriesCount(): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getInStoreSubcategoriesCount();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInStoreSubcategoriesCount();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getOrderedGalleryImages(): Promise<Array<ProcessedImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderedGalleryImages();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderedGalleryImages();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhotoBackgroundImage(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotoBackgroundImage();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotoBackgroundImage();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: bigint): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicesByCategory(arg0: ServiceCategory): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesByCategory(to_candid_ServiceCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesByCategory(to_candid_ServiceCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicesByStoreSubcategory(arg0: StoreServiceCategory): Promise<Array<StoreSubcategoryService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesByStoreSubcategory(to_candid_StoreServiceCategory_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesByStoreSubcategory(to_candid_StoreServiceCategory_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaticDescription(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaticDescription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaticDescription();
            return result;
        }
    }
    async getStoreSubcategoryService(arg0: bigint): Promise<StoreSubcategoryService | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreSubcategoryService(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreSubcategoryService(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getThemeConfig(): Promise<ThemeConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getThemeConfig();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThemeConfig();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTitleGradient(): Promise<GradientConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getTitleGradient();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTitleGradient();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isDemoModeActive(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isDemoModeActive();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDemoModeActive();
            return result;
        }
    }
    async isDemoStateSet(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isDemoStateSet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDemoStateSet();
            return result;
        }
    }
    async removePhotoBackgroundImage(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePhotoBackgroundImage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePhotoBackgroundImage();
            return result;
        }
    }
    async replaceGalleryImage(arg0: bigint, arg1: ExternalBlob | null, arg2: string | null, arg3: AspectRatioOption, arg4: bigint, arg5: string | null, arg6: bigint | null, arg7: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replaceGalleryImage(arg0, await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n66(this._uploadFile, this._downloadFile, arg2), to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replaceGalleryImage(arg0, await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n66(this._uploadFile, this._downloadFile, arg2), to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setBackgroundTheme(arg0: BackgroundTheme): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBackgroundTheme(to_candid_BackgroundTheme_n70(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBackgroundTheme(to_candid_BackgroundTheme_n70(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setDemoState(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDemoState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDemoState();
            return result;
        }
    }
    async setExtendedThemeConfig(arg0: ExtendedThemeConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setExtendedThemeConfig(to_candid_ExtendedThemeConfig_n74(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setExtendedThemeConfig(to_candid_ExtendedThemeConfig_n74(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setHeaderStyleConfig(arg0: HeaderStyleConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHeaderStyleConfig(to_candid_HeaderStyleConfig_n76(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHeaderStyleConfig(to_candid_HeaderStyleConfig_n76(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setThemeConfig(arg0: ThemeConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setThemeConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setThemeConfig(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
    async updateContactInfo(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactInfo(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactInfo(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateImageDescription(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImageDescription(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImageDescription(arg0, arg1);
            return result;
        }
    }
    async updateService(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateServiceWithoutImage(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceWithoutImage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceWithoutImage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateStoreSubcategoryService(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStoreSubcategoryService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStoreSubcategoryService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateStoreSubcategoryServiceWithoutImage(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStoreSubcategoryServiceWithoutImage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStoreSubcategoryServiceWithoutImage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async uploadBanner(arg0: string, arg1: string, arg2: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadBanner(arg0, arg1, await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadBanner(arg0, arg1, await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async uploadCustomerPhoto(arg0: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadCustomerPhoto(await to_candid_ExternalBlob_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadCustomerPhoto(await to_candid_ExternalBlob_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadHeroImage(arg0: ExternalBlob | null, arg1: string, arg2: AspectRatioOption, arg3: bigint, arg4: string | null, arg5: bigint | null, arg6: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadHeroImage(await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadHeroImage(await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async uploadLogoImage(arg0: ExternalBlob | null, arg1: string, arg2: AspectRatioOption, arg3: bigint, arg4: string | null, arg5: bigint | null, arg6: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadLogoImage(await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadLogoImage(await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async uploadPhotoBackgroundImage(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhotoBackgroundImage(await to_candid_ExternalBlob_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhotoBackgroundImage(await to_candid_ExternalBlob_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadProcessedContactBackgroundImage(arg0: ExternalBlob | null, arg1: string, arg2: AspectRatioOption, arg3: bigint, arg4: string | null, arg5: bigint | null, arg6: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProcessedContactBackgroundImage(await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProcessedContactBackgroundImage(await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async uploadProcessedGalleryImage(arg0: ExternalBlob | null, arg1: string, arg2: AspectRatioOption, arg3: bigint, arg4: string | null, arg5: bigint | null, arg6: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProcessedGalleryImage(await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProcessedGalleryImage(await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async uploadProcessedServiceImage(arg0: bigint, arg1: ExternalBlob | null, arg2: AspectRatioOption, arg3: bigint, arg4: string | null, arg5: bigint | null, arg6: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProcessedServiceImage(arg0, await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1), to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProcessedServiceImage(arg0, await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1), to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async uploadProcessedStoreSubcategoryServiceImage(arg0: bigint, arg1: ExternalBlob | null, arg2: AspectRatioOption, arg3: bigint, arg4: string | null, arg5: bigint | null, arg6: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProcessedStoreSubcategoryServiceImage(arg0, await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1), to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProcessedStoreSubcategoryServiceImage(arg0, await to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1), to_candid_AspectRatioOption_n67(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n69(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
}
function from_candid_AspectRatioOption_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AspectRatioOption): AspectRatioOption {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_BackgroundTheme_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackgroundTheme): BackgroundTheme {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_BannerInfo_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BannerInfo): Promise<BannerInfo> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_ExtendedThemeConfig_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtendedThemeConfig): ExtendedThemeConfig {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_HeaderStyleConfig_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeaderStyleConfig): HeaderStyleConfig {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_ImageType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImageType): ImageType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PatternType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatternType): PatternType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_ProcessedImage_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProcessedImage): Promise<ProcessedImage> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_Service_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Promise<Service> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_StoreServiceCategory_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreServiceCategory): StoreServiceCategory {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_StoreSubcategoryService_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreSubcategoryService): Promise<StoreSubcategoryService> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProcessedImage]): Promise<ProcessedImage | null> {
    return value.length === 0 ? null : await from_candid_ProcessedImage_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BannerInfo]): Promise<BannerInfo | null> {
    return value.length === 0 ? null : await from_candid_BannerInfo_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ColorHarmony]): ColorHarmony | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactFormEntry]): ContactFormEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtendedThemeConfig]): ExtendedThemeConfig | null {
    return value.length === 0 ? null : from_candid_ExtendedThemeConfig_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ThemeConfig]): ThemeConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GradientConfig]): GradientConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HeaderStyleConfig]): HeaderStyleConfig | null {
    return value.length === 0 ? null : from_candid_HeaderStyleConfig_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShadowConfig]): ShadowConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LayoutConfig]): LayoutConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TextureConfig]): TextureConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResponsiveConfig]): ResponsiveConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TypographyConfig]): TypographyConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Promise<Service | null> {
    return value.length === 0 ? null : await from_candid_Service_n15(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StoreSubcategoryService]): Promise<StoreSubcategoryService | null> {
    return value.length === 0 ? null : await from_candid_StoreSubcategoryService_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    isActive: boolean;
    category: _ServiceCategory;
    image: [] | [_ProcessedImage];
    price: bigint;
}): Promise<{
    id: bigint;
    name: string;
    description: string;
    isActive: boolean;
    category: ServiceCategory;
    image?: ProcessedImage;
    price: bigint;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        category: from_candid_ServiceCategory_n17(_uploadFile, _downloadFile, value.category),
        image: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.image)),
        price: value.price
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    optimizedUrl: [] | [string];
    originalWidth: [] | [bigint];
    imageType: _ImageType;
    originalHeight: [] | [bigint];
    sortOrder: bigint;
    fileSizeBytes: bigint;
    description: string;
    image: [] | [_ExternalBlob];
    uploadTime: _Time;
    aspectRatio: _AspectRatioOption;
}): Promise<{
    id: bigint;
    optimizedUrl?: string;
    originalWidth?: bigint;
    imageType: ImageType;
    originalHeight?: bigint;
    sortOrder: bigint;
    fileSizeBytes: bigint;
    description: string;
    image?: ExternalBlob;
    uploadTime: Time;
    aspectRatio: AspectRatioOption;
}> {
    return {
        id: value.id,
        optimizedUrl: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.optimizedUrl)),
        originalWidth: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.originalWidth)),
        imageType: from_candid_ImageType_n23(_uploadFile, _downloadFile, value.imageType),
        originalHeight: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.originalHeight)),
        sortOrder: value.sortOrder,
        fileSizeBytes: value.fileSizeBytes,
        description: value.description,
        image: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.image)),
        uploadTime: value.uploadTime,
        aspectRatio: from_candid_AspectRatioOption_n27(_uploadFile, _downloadFile, value.aspectRatio)
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    subcategory: _StoreServiceCategory;
    name: string;
    description: string;
    isActive: boolean;
    image: [] | [_ProcessedImage];
    price: bigint;
}): Promise<{
    id: bigint;
    subcategory: StoreServiceCategory;
    name: string;
    description: string;
    isActive: boolean;
    image?: ProcessedImage;
    price: bigint;
}> {
    return {
        id: value.id,
        subcategory: from_candid_StoreServiceCategory_n32(_uploadFile, _downloadFile, value.subcategory),
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        image: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.image)),
        price: value.price
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pattern: _PatternType;
    baseColor: string;
    patternIntensity: bigint;
    transparencyLevel: bigint;
}): {
    pattern: PatternType;
    baseColor: string;
    patternIntensity: bigint;
    transparencyLevel: bigint;
} {
    return {
        pattern: from_candid_PatternType_n37(_uploadFile, _downloadFile, value.pattern),
        baseColor: value.baseColor,
        patternIntensity: value.patternIntensity,
        transparencyLevel: value.transparencyLevel
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    message: string;
    image: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    message: string;
    image?: ExternalBlob;
}> {
    return {
        name: value.name,
        message: value.message,
        image: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    harmonyLevel: bigint;
    theme: [] | [_ThemeConfig];
    gradient: [] | [_GradientConfig];
    luxuryPreset: boolean;
    headerStyle: [] | [_HeaderStyleConfig];
    colorHarmony: [] | [_ColorHarmony];
}): {
    harmonyLevel: bigint;
    theme?: ThemeConfig;
    gradient?: GradientConfig;
    luxuryPreset: boolean;
    headerStyle?: HeaderStyleConfig;
    colorHarmony?: ColorHarmony;
} {
    return {
        harmonyLevel: value.harmonyLevel,
        theme: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.theme)),
        gradient: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.gradient)),
        luxuryPreset: value.luxuryPreset,
        headerStyle: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.headerStyle)),
        colorHarmony: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.colorHarmony))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shadow: [] | [_ShadowConfig];
    gradient: [] | [_GradientConfig];
    layout: [] | [_LayoutConfig];
    isResponsive: boolean;
    texture: [] | [_TextureConfig];
    responsive: [] | [_ResponsiveConfig];
    colorHarmony: [] | [_ColorHarmony];
    typography: [] | [_TypographyConfig];
}): {
    shadow?: ShadowConfig;
    gradient?: GradientConfig;
    layout?: LayoutConfig;
    isResponsive: boolean;
    texture?: TextureConfig;
    responsive?: ResponsiveConfig;
    colorHarmony?: ColorHarmony;
    typography?: TypographyConfig;
} {
    return {
        shadow: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.shadow)),
        gradient: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.gradient)),
        layout: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.layout)),
        isResponsive: value.isResponsive,
        texture: record_opt_to_undefined(from_candid_opt_n57(_uploadFile, _downloadFile, value.texture)),
        responsive: record_opt_to_undefined(from_candid_opt_n58(_uploadFile, _downloadFile, value.responsive)),
        colorHarmony: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.colorHarmony)),
        typography: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.typography))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStore: null;
} | {
    online: null;
}): ServiceCategory {
    return "inStore" in value ? ServiceCategory.inStore : "online" in value ? ServiceCategory.online : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: null;
} | {
    hero: null;
} | {
    logo: null;
} | {
    photoBackground: null;
} | {
    contactBackground: null;
} | {
    gallery: null;
}): ImageType {
    return "service" in value ? ImageType.service : "hero" in value ? ImageType.hero : "logo" in value ? ImageType.logo : "photoBackground" in value ? ImageType.photoBackground : "contactBackground" in value ? ImageType.contactBackground : "gallery" in value ? ImageType.gallery : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    square: null;
} | {
    portrait: null;
} | {
    original: null;
} | {
    landscape: null;
}): AspectRatioOption {
    return "square" in value ? AspectRatioOption.square : "portrait" in value ? AspectRatioOption.portrait : "original" in value ? AspectRatioOption.original : "landscape" in value ? AspectRatioOption.landscape : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    operatorService: null;
} | {
    selfService: null;
}): StoreServiceCategory {
    return "operatorService" in value ? StoreServiceCategory.operatorService : "selfService" in value ? StoreServiceCategory.selfService : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    waterRipples: null;
} | {
    bubbles: null;
} | {
    fabricTexture: null;
}): PatternType {
    return "waterRipples" in value ? PatternType.waterRipples : "bubbles" in value ? PatternType.bubbles : "fabricTexture" in value ? PatternType.fabricTexture : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Promise<Array<Service>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Service_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoreSubcategoryService>): Promise<Array<StoreSubcategoryService>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StoreSubcategoryService_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProcessedImage>): Promise<Array<ProcessedImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ProcessedImage_n20(_uploadFile, _downloadFile, x)));
}
function to_candid_AspectRatioOption_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AspectRatioOption): _AspectRatioOption {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function to_candid_BackgroundTheme_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackgroundTheme): _BackgroundTheme {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_ExtendedThemeConfig_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExtendedThemeConfig): _ExtendedThemeConfig {
    return to_candid_record_n75(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_HeaderStyleConfig_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeaderStyleConfig): _HeaderStyleConfig {
    return to_candid_record_n77(_uploadFile, _downloadFile, value);
}
function to_candid_ImageType_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageType): _ImageType {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_PatternType_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatternType): _PatternType {
    return to_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_StoreServiceCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoreServiceCategory): _StoreServiceCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n65(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pattern: PatternType;
    baseColor: string;
    patternIntensity: bigint;
    transparencyLevel: bigint;
}): {
    pattern: _PatternType;
    baseColor: string;
    patternIntensity: bigint;
    transparencyLevel: bigint;
} {
    return {
        pattern: to_candid_PatternType_n72(_uploadFile, _downloadFile, value.pattern),
        baseColor: value.baseColor,
        patternIntensity: value.patternIntensity,
        transparencyLevel: value.transparencyLevel
    };
}
function to_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    harmonyLevel: bigint;
    theme?: ThemeConfig;
    gradient?: GradientConfig;
    luxuryPreset: boolean;
    headerStyle?: HeaderStyleConfig;
    colorHarmony?: ColorHarmony;
}): {
    harmonyLevel: bigint;
    theme: [] | [_ThemeConfig];
    gradient: [] | [_GradientConfig];
    luxuryPreset: boolean;
    headerStyle: [] | [_HeaderStyleConfig];
    colorHarmony: [] | [_ColorHarmony];
} {
    return {
        harmonyLevel: value.harmonyLevel,
        theme: value.theme ? candid_some(value.theme) : candid_none(),
        gradient: value.gradient ? candid_some(value.gradient) : candid_none(),
        luxuryPreset: value.luxuryPreset,
        headerStyle: value.headerStyle ? candid_some(to_candid_HeaderStyleConfig_n76(_uploadFile, _downloadFile, value.headerStyle)) : candid_none(),
        colorHarmony: value.colorHarmony ? candid_some(value.colorHarmony) : candid_none()
    };
}
function to_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shadow?: ShadowConfig;
    gradient?: GradientConfig;
    layout?: LayoutConfig;
    isResponsive: boolean;
    texture?: TextureConfig;
    responsive?: ResponsiveConfig;
    colorHarmony?: ColorHarmony;
    typography?: TypographyConfig;
}): {
    shadow: [] | [_ShadowConfig];
    gradient: [] | [_GradientConfig];
    layout: [] | [_LayoutConfig];
    isResponsive: boolean;
    texture: [] | [_TextureConfig];
    responsive: [] | [_ResponsiveConfig];
    colorHarmony: [] | [_ColorHarmony];
    typography: [] | [_TypographyConfig];
} {
    return {
        shadow: value.shadow ? candid_some(value.shadow) : candid_none(),
        gradient: value.gradient ? candid_some(value.gradient) : candid_none(),
        layout: value.layout ? candid_some(value.layout) : candid_none(),
        isResponsive: value.isResponsive,
        texture: value.texture ? candid_some(value.texture) : candid_none(),
        responsive: value.responsive ? candid_some(value.responsive) : candid_none(),
        colorHarmony: value.colorHarmony ? candid_some(value.colorHarmony) : candid_none(),
        typography: value.typography ? candid_some(value.typography) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    inStore: null;
} | {
    online: null;
} {
    return value == ServiceCategory.inStore ? {
        inStore: null
    } : value == ServiceCategory.online ? {
        online: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoreServiceCategory): {
    operatorService: null;
} | {
    selfService: null;
} {
    return value == StoreServiceCategory.operatorService ? {
        operatorService: null
    } : value == StoreServiceCategory.selfService ? {
        selfService: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageType): {
    service: null;
} | {
    hero: null;
} | {
    logo: null;
} | {
    photoBackground: null;
} | {
    contactBackground: null;
} | {
    gallery: null;
} {
    return value == ImageType.service ? {
        service: null
    } : value == ImageType.hero ? {
        hero: null
    } : value == ImageType.logo ? {
        logo: null
    } : value == ImageType.photoBackground ? {
        photoBackground: null
    } : value == ImageType.contactBackground ? {
        contactBackground: null
    } : value == ImageType.gallery ? {
        gallery: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AspectRatioOption): {
    square: null;
} | {
    portrait: null;
} | {
    original: null;
} | {
    landscape: null;
} {
    return value == AspectRatioOption.square ? {
        square: null
    } : value == AspectRatioOption.portrait ? {
        portrait: null
    } : value == AspectRatioOption.original ? {
        original: null
    } : value == AspectRatioOption.landscape ? {
        landscape: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatternType): {
    waterRipples: null;
} | {
    bubbles: null;
} | {
    fabricTexture: null;
} {
    return value == PatternType.waterRipples ? {
        waterRipples: null
    } : value == PatternType.bubbles ? {
        bubbles: null
    } : value == PatternType.fabricTexture ? {
        fabricTexture: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
